events/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'events.views.list_event', name='event-list'),
    url(r'^search/$', 'events.views.search_events', name='events-list'),
    url(r'^list/$', 'events.views.list_event_api', name='event-list-api'),
    url(r'^add/$', 'events.views.add_event', name='add-event'),
    url(r'^edit/(?P<id>\w+)/$', 'events.views.edit_event', name='edit-events'),
    url(r'^delete/$', 'events.views.delete_event', name='delete-events'),
    url(r'^view/(?P<id>\w+)/$', 'events.views.events_details', name='events-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),
   
    url(r'^controllers/$', 'events.views.list_controller', name='controller-list'),
    url(r'^controller-list/$', 'events.views.controller_list', name='list-controller'),
    url(r'^controllers/add/$', 'events.views.add_controller', name='add-controller'),
    url(r'^controllers/edit/(?P<controller_name>[\w ,\']+)/$', 'events.views.edit_controller', name='edit-controller'),
    url(r'^controllers/delete/$', 'events.views.delete_controller', name='delete-controller'),
    url(r'^controllers/view/(?P<controller_name>[\w ,\']+)/$', 'events.views.controller_details', name='controller-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),


    url(r'^evententry/add/$', 'events.views.add_evententry', name='add-event-entry'),
    url(r'^evententry/delete/$', 'events.views.delete_evententry', name='delete-event-entry'),
    url(r'^evententry/edit/(?P<entryid>[\w ,\']+)/$', 'events.views.edit_evententry', name='edit-event-entry'),
    url(r'^evententry/view/(?P<entryid>[\w ,\']+)/$', 'events.views.view_evententry', name='view-event-entry'),
    url(r'^entry/list/$', 'events.views.list_evententry', name='list-event-entry'),
    
    url(r'^event-entry-list/$', 'events.views.list_evententry_api', name='list-event-entry-api'),


    url(r'^eventpayroll/add/$', 'events.views.add_eventpayroll', name='add-event-payroll'),
    url(r'^payroll/delete/$', 'events.views.delete_eventpayroll', name='delete-event-payroll'),
    url(r'^payroll/edit/(?P<serial_id>[\w ,\']+)/$', 'events.views.edit_eventpayroll', name='edit-event-payroll'),
    url(r'^payroll/view/(?P<serial_id>[\w ,\']+)/$', 'events.views.view_eventpayroll', name='view-event-payroll'),
    url(r'^payroll/list/$', 'events.views.list_eventpayroll', name='list-event-payroll'),
   
)

imeter24/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'imeter24.views.home', name='home'),

    url(r'^generate-pdf/$', 'imeter24.views.generate_pdf', name='generate-pdf'),

    url(r'^system-variable/$', 'imeter24.views.sys_variable', name='sys-variable'),
    
    url(r'^dashboard/$', 'imeter24.views.dashboard', name='user-dashboard'),

    url(r'^send-mass-mail/$', 'imeter24.views.send_mass_mail', name='send-mass-mail'),
    url(r'^mass-mail-status/$', 'imeter24.views.mass_mail_status', name='mass-mail-status'),
    url(r'^get-mass-mails/$', 'imeter24.views.get_mass_mails', name='get-mass-mail'),
    
    url(r'^group/add/$', 'imeter24.views.add_group', name='add-group'),
    url(r'^group/list/$', 'imeter24.views.list_group', name='list-group'),
    url(r'^group/delete/$', 'imeter24.views.delete_group', name='delete-group'),

    #======= Angular route ===========
    url(r'^userlist/$', 'scomuser.views.UserListApi', name='userlistapi'),

    url(r'^group/edit/(?P<group_id>\d+)/$', 'imeter24.views.edit_group', name='edit-group'),
    url(r'^group/view/(?P<group_id>\d+)/$', 'imeter24.views.group_details', name='view-group'),

    url(r'^group/update/$', 'imeter24.views.update_group', name='update-group'),
    url(r'^scomuser/', include('scomuser.urls')),
    url(r'^contacts/', include('contacts.urls')),
    # url(r'^inventory/', include('inventory.urls')),
    # url(r'^report/', include('report.urls')),
    # url(r'^events/', include('events.urls')),
    # url(r'^purchase/', include('purchase.urls')),

    url(r'^controllers/', include('controllers.urls')),


    # url(r'^schedule/', include('schedule.urls')),

    url(r'^statics/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    )

inventory/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^items/$', 'inventory.views.list_item', name='item-list'),
    url(r'^search/$', 'inventory.views.search_item', name='item-search'),
    url(r'^auto/$', 'inventory.views.autocomplete', name='item-sugessions'),

    url(r'^get-item/(?P<itemnumber>[\w ,\'-]+)/$', 'inventory.views.get_item', name='get-item'),
    url(r'^filter-items/$', 'inventory.views.get_filtered_items', name='filter-items'),
    url(r'^list/$', 'inventory.views.inventory_items', name='inventory-list'),
    # url(r'^item/add/$', 'inventory.views.add_item', name='add-item'),
    url(r'^item/add/$', 'inventory.views.add_new_item', name='add-new-item'),
    url(r'^item/add-another/$', 'inventory.views.add_another_item', name='add-another-item'),
    url(r'^item/delete/$', 'inventory.views.delete_item', name='delete-item'),
    url(r'^item/edit/(?P<itemid>[\w ,\'-]+)/$', 'inventory.views.edit_item', name='edit-item'),
    url(r'^item/view/(?P<itemid>[\w ,\'-]+)/$', 'inventory.views.item_details', name='item-details'),
    url(r'^item/filter/$', 'inventory.views.item_details_filtered', name='item-details-filtered'),

    url(r'^item/comment/add/$', 'inventory.views.add_item_comment', name='add-item-comment'),

    url(r'^deliverinternal-list/$', 'inventory.views.list_deliverinternal', name='list-purchase-deliverinternal'),
    url(r'^deliverinternals/json/$', 'inventory.views.list_deliverinternal_json', name='list-purchase-deliverinternal-json'),
    url(r'^deliverinternal/add/$', 'inventory.views.add_deliverinternal', name='add-purchase-deliverinternal'),
    url(r'^deliverinternal/edit/(?P<id>\d+)/$', 'inventory.views.edit_deliverinternal', name='edit-purchase-deliverinternal'),
    url(r'^deliverinternal/delete/$', 'inventory.views.delete_deliverinternal', name='delete-purchase-deliverinternal'),

    url(r'^unit-measure-list/$', 'inventory.views.list_unit_measue', name='list-inventory-unit-measure'),
    url(r'^unit-measure-list/json/$', 'inventory.views.list_unit_measue_json2'),
    url(r'^unit-measure/add/$', 'inventory.views.add_unit_measue', name='add-inventory-unit-measure'),
    url(r'^unit-measure/edit/(?P<unit_mes_id>\w+)/$', 'inventory.views.edit_unit_measue', name='edit-inventory-unit-measure'),
    url(r'^unit-measure/delete/$', 'inventory.views.delete_unit_measue', name='delete-inventory-unit-measure'),


    url(r'^production-type-list/$', 'inventory.views.list_production_type', name='list-inventory-production-type'),
    url(r'^production-type/add/$', 'inventory.views.add_production_type', name='add-inventory-production-type'),
    url(r'^production-type/edit/(?P<prod_type_id>\w+)/$', 'inventory.views.edit_production_type', name='edit-inventory-production-type'),
    url(r'^production-type/delete/$', 'inventory.views.delete_production_type', name='delete-inventory-production-type'),


    url(r'^custom-designation-list/$', 'inventory.views.list_custom_designation', name='list-custom-designation-type'),
    url(r'^custom-designation/add/$', 'inventory.views.add_custom_designation', name='add-custom-designation-type'),
    url(r'^custom-designation/edit/(?P<cus_des_id>\w+)/$', 'inventory.views.edit_custom_designation', name='edit-custom-designation-type'),
    url(r'^custom-designation/delete/$', 'inventory.views.delete_custom_designation', name='delete-custom-designation-type'),


    url(r'^location-list/$', 'inventory.views.list_location', name='list-inventory-location'),
    url(r'^location/add/$', 'inventory.views.add_location', name='add-inventory-location'),
    url(r'^location/edit/(?P<loc_id>\d+)/$', 'inventory.views.edit_location', name='edit-inventory-location'),
    url(r'^location/delete/$', 'inventory.views.delete_location', name='delete-inventory-location'),

    url(r'^item/reindex/$', 'inventory.views.item_reindex', name='item-reindex'),
    
)

inventory/models.py
from django.db import models
from contacts.models import *
from scomuser.models import *
from inventory.choices import *
# from purchase.models import DeliverInternal
# Create your models here.

class DeliverInternal(models.Model):
	department = models.CharField(max_length=50, blank=True, null=True, help_text="BIN # in warehouse")
	description = models.TextField(blank=True, null=True)

	def __unicode__(self):
		return self.department

	class Meta:
		verbose_name = "Deliver Internal"
		verbose_name_plural = "Deliver Internals"

		permissions = (
    		('view_deliverinternal', 'Can View Deliver Internal'),
    	)

class ItemUnitMeasure(models.Model):
	unit_name = models.CharField(max_length=20, null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.unit_name

	class Meta:
		verbose_name = "Item Unit Measure"
		verbose_name_plural = "Item Unit Measure"

		permissions = (
    		('view_itemunitmeasure', 'Can View Item Unit Measure'),
    	)

class ProductionType(models.Model):
	production_type_name = models.CharField(max_length=20, null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.production_type_name

	class Meta:
		verbose_name = "Production Type Name"
		verbose_name_plural = "Production Type Names"

		permissions = (
    		('view_productiontype', 'Can View Production Type Name'),
    	)

class CustomsDesignation(models.Model):
	designation = models.CharField(max_length=20, null=True, blank=True)
	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

	def __unicode__(self):
		return self.designation

	class Meta:
		verbose_name = "Designation"
		verbose_name_plural = "Designations"

		permissions = (
    		('view_customsdesignation', 'Can View Custom Designation'),
    	)

class Location(models.Model):
	warehouse_location = models.CharField(max_length=50, blank=True, null=True, help_text="BIN # in warehouse")
	description = models.TextField(blank=True, null=True)

	def __unicode__(self):
		return self.warehouse_location

	class Meta:
		verbose_name = "Location"
		verbose_name_plural = "Locations"

		permissions = (
    		('view_location', 'Can View Location'),
    	)

class Item(models.Model):
	item_number = models.CharField(max_length=20, primary_key=True)
	description  = models.TextField(blank=True, null=True)
	quantity_on_hand = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True, default=0.0)
	department = models.ForeignKey(Department, blank=True, null=True)
	quantity_on_order = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
	primary_supplier = models.ForeignKey(Contact, blank=True, null=True, related_name='item_supplier')
	
	'''
	last_PO, date_ordered, date_expected, last_cost_paid = These field will be auto updated with po or invoice
	'''
	qty_received = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
	qty_received_date = models.DateField(blank=True, null=True)
	last_PO = models.CharField(max_length=20, blank=True, null=True)
	last_PO_date_ordered = models.DateField(blank=True, null=True)
	last_PO_date_expected = models.DateField(blank=True, null=True)
	last_cost_paid = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
	last_PO_ordered_by = models.ForeignKey(User, blank=True, null=True, related_name='last_PO_order_by')
	last_PO_supplier = models.ForeignKey(Contact, blank=True, null=True, related_name='last_PO_supplier')
	
	comments = models.TextField(blank=True, null=True, help_text="Anything entered here will print on reports")
	item_unit_measure = models.ForeignKey(ItemUnitMeasure, blank=True, null=True)
	
	stock_status_type = models.CharField(max_length=10, choices=STOCK_STATUS_TYPE, default="normal")
	currency = models.ForeignKey(Currency, max_length=20, blank=True, null=True)
	warehouse_location = models.CharField(max_length=20, blank=True, null=True)

	lowest_price_supplier = models.ForeignKey(Contact, blank=True, null=True, related_name="economic_supplier")
	lowest_price_paid = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
	lowest_price_last_buy_date = models.DateField(blank=True, null=True)
	lowest_price_last_buy_PO = models.CharField(max_length=20, blank=True, null=True)

	# last_shop_order = models.CharField(max_length=10, blank=True, null=True)
	# shop_order_date = models.DateField(blank=True, null=True)
	# shop_order_expected = models.DateField(blank=True, null=True)
	# shop_order_status = models.CharField(max_length=10, choices=SHOP_STATUS_CHOICES, default="0", blank=False, null=False)
	
	qty_on_request = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
	max_order_qty = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
	max_single_order_qty = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
	# This field value give remaining qty of item for max_order_qty
	max_order_qty_remains = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
	wholesale_cost = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0.0)
	retail_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
	
	estimated_wholesale_cost = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
	
	production_type =  models.ForeignKey(ProductionType, blank=True, null=True)
	catalog_number = models.CharField(max_length=50, blank=True, null=True, help_text = "Supplier part number to use on our POs")
	country_of_origin = models.CharField(max_length=50, blank=True, null=True)
	lead_time = models.CharField(max_length=20, blank=True, null=True, 
		help_text='Enter lead time in English, such as "14 d" or "14 days" or even "3m 2d"')
	customs_designation = models.ForeignKey(CustomsDesignation, blank=True, null=True, 
		help_text="Enter minimum 4 digit WCO HS code for exporting.")
	customer_tariff_number  = models.CharField(max_length=50, blank=True, null=True)
	preference_criteria = models.CharField(max_length=50, blank=True, null=True)
	producer_of_item = models.ForeignKey(Contact, blank=True, null=True)
	shipping_unit = models.CharField(max_length=50, blank=True, null=True)
	shipping_weight = models.CharField(max_length=50, blank=True, null=True)
	minimum_qty_on_hand = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
	duty_percentage = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
	# notes = GenericRelation(Comment, object_id_field='object_pk', 
	# 	help_text=_("Anything entered here can only be displayed online."))
	# site = models.ForeignKey(Contact, blank=True, null=True, related_name='item-site',
	#  	help_text="Indicate which contact/site this record belongs to")
	hst_taxable = models.BooleanField(verbose_name="HST Taxable", default=True)
	pst_taxable = models.BooleanField(verbose_name="PST Taxable", default=True)
	website = models.URLField(blank=True, null=True, max_length=250)
	item_image = models.ImageField(upload_to='item_image', blank=True, null=True)
	date_added = models.DateTimeField('date added', auto_now_add=True)
	date_modified = models.DateTimeField('date modified', auto_now=True)
	deliver_internal = models.ForeignKey(DeliverInternal, blank=True, null=True)
	terms = models.ForeignKey(PaymentTerm, blank=True, null=True, related_name='item_payment_terms')
	search_string 	  = models.TextField(null=True, blank=True, verbose_name='Search String')

	def __unicode__(self):
		return self.item_number

	def get_currency(self):
		if self.currency:
			pass
	
	@property	
	def order_restriction(self):
		if self.max_order_qty_remains and self.max_single_order_qty:
			if self.max_order_qty_remains <= self.max_single_order_qty:
				return self.max_order_qty_remains
			else:
				return self.max_single_order_qty
		else:
			return self.max_single_order_qty

	class Meta:
		verbose_name = "Item"
		verbose_name_plural = "Items"

		permissions = (
    		('view_item', 'Can View Item'),
    	)

class ItemComment(models.Model):
	item = models.ForeignKey(Item, blank=True, null=True)
	comment = models.TextField(null=True, blank=True, verbose_name='Item Comment')
	comment_date = models.DateTimeField('comment date', auto_now=True)
	comment_by = models.ForeignKey(User, blank=True, null=True)

	def __unicode__(self):
		return self.item.item_number

	class Meta:
		verbose_name = "ItemComment"
		verbose_name_plural = "Item Comments"

		permissions = (
    		('view_itemcomment', 'Can View Item comment'),
    	)

templates/inventory/production-type/add-list-production-type.html
{% extends "base.html" %}

{% block content %}

<div class="container shadow4 main-body">

<section class="row"  id="production-type">
	

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
		    	<h4>Production Type List</h4>
		  	</div>
		  	<div class="panel-body">
		  	<form name="production-type-form">
		  		<div class="input-group">
				  	{% for field in production_type_form %}
				  		{{ field }}
				  	{% endfor %}
				  	<div class="input-group-btn">
						<button class="btn btn-primary" type="submit">Add Production Type</button>
					</div>
				</div>
		  	</form>
			</div>
		</div>
	</div>

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-body">
				<div id="production-type-list">
				{% for production_type in production_types %}
					{% include "inventory/production-type/add-production-type-partial.html" %}
				{% endfor %}
				</div>
			</div>
		</div>

	</div>

{% include "modals/edit-modal.html" %}


<script type="text/javascript">
	(function(){

		$("a.production-type-edit").on("click", function(e){
			e.preventDefault();
			// com_id = $(this).data("id");
		    url = $(this).attr("href");
			mdal = $('#editModal');
			mdal.on("shown.bs.modal", function(){
				$("#editModal .modal-content").load(url);
				console.log(url);
			}).modal();

			return false;
		});

		$("form[name='production-type-form']").on("submit", function(e){
			e.preventDefault();
			form_data = $(this).serialize();

			$.ajax({
				type: "POST",
				url: "/inventory/production-type/add/",
				data: form_data,
				success: function(rdata) {
					$("#production-type-list").append(rdata);
					console.log(rdata);
				},
				errors: function() {

				}
			})

		})

	})(jQuery)


</script>



</section>
</div>


{% endblock content %}
	

templates/inventory/production-type/add-production-type-partial.html
<span class="label label-danger {{ production_type.id }}">
	{{ production_type.production_type_name }}
	{% if perms.inventory.change_productiontype %}
		<a class="production-type-edit" href="/inventory/production-type/edit/{{ production_type.id }}/" 
			data-toggle="modal" data-target="#editModal"
			data-prod-type-id="{{ production_type.id }}"><i class="glyphicon glyphicon-edit"></i></a>
	{% endif %}
</span>

templates/inventory/production-type/edit-production-type-tmpl.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Edit Production Type</h4>
</div>
<form name="production-type" action="/inventory/production-type/edit/{{ prod_type_id }}/" method="post">{% csrf_token %}
<div class="modal-body" style="text-align: center;">
    
    <input type="hidden" name="prod_type_id" value="{{ prod_type_id }}">
    <table>
        <tr>
        {% for field in production_type_form %}
            <td>
                {{ field }}
            </td>
        {% endfor %}
        
        </tr>
    </table>
    
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save changes</button>
</div>
</form>
<script type="text/javascript">
(function(){
    $("form[name='production-type']").on("submit", function(e){
        e.preventDefault();
        id = $("input[name='prod_type_id']").val();
        $("#production-type-list span."+id).remove();
        console.log(id);
        
        form_data = $(this).serialize();
        $.ajax({
            type: "POST",
            url: $(this).attr("action"),
            data: form_data,
            success: function(rdata) {
                $( "button.close-modal" ).trigger( "click" );

                $("#production-type-list").prepend(rdata);

            }
        })

    })

})(jQuery)
    
</script>

templates/inventory/production-type/list-production-type.html
{% extends "base.html" %}

{% block content %}

<div class="container shadow4 main-body">

<section class="row"  id="production-type-list">
	

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
		    	<h4> Production Type</h4>
		  	</div>
		  	<div class="panel-body">
		  		<table class="table">
			  		<tr>
			  			<td> ID </td>
			  			<td>Production Type </td>
			  			<td>Total Use</td>
			  			<td>Action</td>
			  			
			  		</tr>
			  		{% for production_type in production_types %}
			  			<tr>
				  			<td> {{ production_type.id }} </td>
				  			<td> {{ production_type.production_type_name }} </td>
				  			<td> {{ production_type.item_set.all.count }} </td>
				  			<td>
				  				<a class="production-type-delete" href="#" data-prod-type-id="{{ production_type.id }}">delete</a>
				  			</td>
				  			
				  		</tr>
				  	{% empty %}
				  	<tr>
			  			<td colspan='4'> No Production Type found. </td>
			  		</tr>
				  	{% endfor %}
			  	</table>
		  	
			</div>
		</div>
	</div>


</section>

<script type="text/javascript">
(function(){
	$("#production-type-list a.production-type-delete").on("click", function(e){
		e.preventDefault();
		prodid = $(this).data("prod-type-id");
		console.log(prodid);

		$.ajax({
			type: "POST",
			url: "/inventory/production-type/delete/",
			data: {
				'production_type_id': prodid,
			},
			success: function(rdata) {
				console.log(rdata);
				$("a[data-prod-type-id='"+rdata+"']").closest("tr").remove();
			}
		})
	});

})(jQuery)

</script>
</div>


{% endblock content %}
	