events/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'events.views.list_event', name='event-list'),
    url(r'^search/$', 'events.views.search_events', name='events-list'),
    url(r'^list/$', 'events.views.list_event_api', name='event-list-api'),
    url(r'^add/$', 'events.views.add_event', name='add-event'),
    url(r'^edit/(?P<id>\w+)/$', 'events.views.edit_event', name='edit-events'),
    url(r'^delete/$', 'events.views.delete_event', name='delete-events'),
    url(r'^view/(?P<id>\w+)/$', 'events.views.events_details', name='events-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),
   
    url(r'^controllers/$', 'events.views.list_controller', name='controller-list'),
    url(r'^controller-list/$', 'events.views.controller_list', name='list-controller'),
    url(r'^controllers/add/$', 'events.views.add_controller', name='add-controller'),
    url(r'^controllers/edit/(?P<controller_name>[\w ,\']+)/$', 'events.views.edit_controller', name='edit-controller'),
    url(r'^controllers/delete/$', 'events.views.delete_controller', name='delete-controller'),
    url(r'^controllers/view/(?P<controller_name>[\w ,\']+)/$', 'events.views.controller_details', name='controller-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),


    url(r'^evententry/add/$', 'events.views.add_evententry', name='add-event-entry'),
    url(r'^evententry/delete/$', 'events.views.delete_evententry', name='delete-event-entry'),
    url(r'^evententry/edit/(?P<entryid>[\w ,\']+)/$', 'events.views.edit_evententry', name='edit-event-entry'),
    url(r'^evententry/view/(?P<entryid>[\w ,\']+)/$', 'events.views.view_evententry', name='view-event-entry'),
    url(r'^entry/list/$', 'events.views.list_evententry', name='list-event-entry'),
    
    url(r'^event-entry-list/$', 'events.views.list_evententry_api', name='list-event-entry-api'),


    url(r'^eventpayroll/add/$', 'events.views.add_eventpayroll', name='add-event-payroll'),
    url(r'^payroll/delete/$', 'events.views.delete_eventpayroll', name='delete-event-payroll'),
    url(r'^payroll/edit/(?P<serial_id>[\w ,\']+)/$', 'events.views.edit_eventpayroll', name='edit-event-payroll'),
    url(r'^payroll/view/(?P<serial_id>[\w ,\']+)/$', 'events.views.view_eventpayroll', name='view-event-payroll'),
    url(r'^payroll/list/$', 'events.views.list_eventpayroll', name='list-event-payroll'),
   
)

imeter24/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'imeter24.views.home', name='home'),

    url(r'^generate-pdf/$', 'imeter24.views.generate_pdf', name='generate-pdf'),

    url(r'^system-variable/$', 'imeter24.views.sys_variable', name='sys-variable'),
    
    url(r'^dashboard/$', 'imeter24.views.dashboard', name='user-dashboard'),

    url(r'^send-mass-mail/$', 'imeter24.views.send_mass_mail', name='send-mass-mail'),
    url(r'^mass-mail-status/$', 'imeter24.views.mass_mail_status', name='mass-mail-status'),
    url(r'^get-mass-mails/$', 'imeter24.views.get_mass_mails', name='get-mass-mail'),
    
    url(r'^group/add/$', 'imeter24.views.add_group', name='add-group'),
    url(r'^group/list/$', 'imeter24.views.list_group', name='list-group'),
    url(r'^group/delete/$', 'imeter24.views.delete_group', name='delete-group'),

    #======= Angular route ===========
    url(r'^userlist/$', 'scomuser.views.UserListApi', name='userlistapi'),

    url(r'^group/edit/(?P<group_id>\d+)/$', 'imeter24.views.edit_group', name='edit-group'),
    url(r'^group/view/(?P<group_id>\d+)/$', 'imeter24.views.group_details', name='view-group'),

    url(r'^group/update/$', 'imeter24.views.update_group', name='update-group'),
    url(r'^scomuser/', include('scomuser.urls')),
    url(r'^contacts/', include('contacts.urls')),
    # url(r'^inventory/', include('inventory.urls')),
    # url(r'^report/', include('report.urls')),
    # url(r'^events/', include('events.urls')),
    # url(r'^purchase/', include('purchase.urls')),

    url(r'^controllers/', include('controllers.urls')),


    # url(r'^schedule/', include('schedule.urls')),

    url(r'^statics/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    )

report/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^list/$', 'report.views.list_report', name='report-list'),
    url(r'^list/api/$', 'report.views.list_report_api', name='report-list-api'),
    
    url(r'^add/$', 'report.views.add_report', name='add-report'),
    url(r'^delete/$', 'report.views.delete_report', name='delete-report'),
    url(r'^edit/(?P<id>[\w -]+)/$', 'report.views.edit_report', name='edit-report'),
    url(r'^view/(?P<id>[\w -]+)/$', 'report.views.report_details', name='report-details'),
    url(r'^view/api/(?P<id>[\w -]+)/$', 'report.views.report_details_api', name='report-details'),
    url(r'^view/$', 'report.views.report_view', name='report-view'),

    url(r'^recuring/add/$', 'report.views.add_recuring_report', name='add-recuring-report'),
    url(r'^recuring/delete/$', 'report.views.delete_recuring_report', name='delete-recuring-report'),
    url(r'^recuring/view/(?P<id>[\w -]+)/$', 'report.views.view_recuring_report', name='view-recuring-report'),
    url(r'^recuring/edit/(?P<id>[\w -]+)/$', 'report.views.edit_recuring_report', name='edit-recuring-report'),

    url(r'^singlejob/add/$', 'report.views.add_single_report', name='add-single-report'),
    url(r'^singlejob/view/(?P<id>[\w -]+)/$', 'report.views.view_single_report', name='view-single-report'),
    url(r'^singlejob/api/(?P<jobid>[\w -]+)/$', 'report.views.single_report_api', name='api-single-report'),
    url(r'^singlejob/edit/(?P<id>[\w -]+)/$', 'report.views.edit_single_report', name='edit-single-report'),
    url(r'^singlejob/delete/$', 'report.views.delete_single_report', name='delete-single-report'),

    url(r'^recuring/job/api/(?P<id>[\w -]+)/$', 'report.views.recuring_job_json', name='recuring-job-api'),

    url(r'^lists/$', 'report.views.recuring_report_list', name='list-recuring-report'),
    url(r'^recuring-job-list/$', 'report.views.list_recuring_job', name='report-recuring-list'),
    url(r'^single-job-list/$', 'report.views.list_single_job', name='report-single-list'),

    url(r'^printer/list/$', 'report.views.list_printer', name='list-printer'),
    url(r'^printer/list/api/$', 'report.views.list_printer_api', name='list-printer-api'),
    url(r'^printer/add/$', 'report.views.add_printer', name='add-printer'),
    url(r'^printer/view/(?P<printer_id>[\w -]+)/$', 'report.views.view_printer', name='view-printer'),
    url(r'^printer/edit/(?P<printer_id>[\w -]+)/$', 'report.views.edit_printer', name='edit-printer'),
    url(r'^printer/delete/$', 'report.views.delete_printer', name='delete-printer'),


)

report/models.py
from django.db import models
from report.choices import *

# Create your models here.


# class ReportType(models.Model):
# 	report_type = models.CharField(max_length=20, null=True, blank=True)
# 	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

# 	def __unicode__(self):
# 		return self.report_type

# 	# def natural_key(self):
# 	# 	return self.report_type

# 	class Meta:
# 		verbose_name = "Report Type"
# 		verbose_name_plural = "Report Types"

# 		permissions = (
#     		('view_reporttype', 'Can View Report Type'),
#     	)


# class Printer(models.Model):
# 	printer_name = models.CharField(max_length=20, null=True, blank=True)
# 	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

# 	def __unicode__(self):
# 		return self.printer_name

# 	# def natural_key(self):
# 	# 	return self.printer_name

# 	class Meta:
# 		verbose_name = "Printer Name"
# 		verbose_name_plural = "Printer Names"

# 		permissions = (
#     		('view_printer', 'Can View Printer'),
#     	)

class Printer(models.Model):
	printer_id = models.CharField(max_length=50, primary_key=True)
	# printer_name = models.CharField(max_length=20, null=True, blank=True)
	network_que_location = models.CharField(max_length=200, null=True, blank=True)
	printer_type = models.CharField(max_length=25, choices=PRINTER_TYPE, null=True, blank=True)
	printer_status = models.CharField(max_length=20, choices=PRINTER_STATUS, null=True, blank=True)
	

	def __unicode__(self):
		return self.printer_id

	# def natural_key(self):
	# 	nk = { 'printer_name': self.printer_id}
	# 	return (nk)

	class Meta:
		verbose_name = "Printer"
		verbose_name_plural = "Printers"

		permissions = (
    		('view_printer', 'Can View Printer'),
    	)


class Report(models.Model):
	report_type = models.CharField(max_length=50, blank=True, null=True)
	# printer = models.ForeignKey(Printer, blank=True, null=True)
	destination_type = models.CharField(max_length=20, choices=QUE_TYPE, null=True, blank=True)
	# status = models.CharField(max_length=20, choices=STATUS, null=True, blank=True)
	comments = models.TextField(blank=True, null=True)
	# start_date = models.DateField(blank=True, null=True)
	# end_date = models.DateField(blank=True, null=True)
	# rang = models.CharField(max_length=50, blank=True, null=True)
	python_script = models.CharField(max_length=200, blank=True, null=True)
	search_string = models.CharField(max_length=250, blank=True, null=True)

	def __unicode__(self):
		return self.report_type

	class Meta:
		verbose_name = "report"
		verbose_name_plural = "reports"

		permissions = (
    		('view_report', 'Can View report'),
    	)

class RecuringReport(models.Model):
	report = models.ForeignKey(Report, blank=True, null=True)
	report_description = models.TextField(blank=True, null=True)
	script_name = models.CharField(max_length=200, blank=True, null=True)

	que_type = models.CharField(max_length=20, choices=QUE_TYPE, null=True, blank=True)
	email = models.CharField(max_length=500, blank=True, null=True)
	printer = models.ForeignKey(Printer, blank=True, null=True, default=None)
	fax = models.CharField(max_length=20, blank=True, null=True)
	current_job_status = models.CharField(max_length=50, choices=JOB_STATUS, null=True, blank=True)
	date_submitted = models.DateField(blank=True, null=True)
	time_submitted = models.TimeField(blank=True, null=True)
	date_finished = models.DateField(blank=True, null=True)
	time_finished = models.TimeField(blank=True, null=True)
	# script_name = models.CharField(max_length=50, blank=True, null=True)
	unix_que = models.CharField(max_length=100, blank=True, null=True)
	comment = models.TextField(blank=True, null=True)

	schedule_type = models.CharField(max_length=15, choices=(('weekly', 'Weekly'), ('daily', 'Daily'), ('randomdays', 'Random week days')))
	week_day = models.CharField(max_length=200, blank=True, null=True)
	randomdays = models.CharField(max_length=200, blank=True, null=True)
	daytime = models.CharField(max_length=15, blank=True, null=True)
	search_string = models.CharField(max_length=250, blank=True, null=True)

	def __unicode__(self):
		return "%s - %s" % (self.report.report_type, self.que_type)

	class Meta:
		verbose_name = "recuring report"
		verbose_name_plural = "recuring reports"

		permissions = (
    		('view_recuringreport', 'Can View recuring report'),
    	)


class SingleReport(models.Model):
	report = models.ForeignKey(Report, blank=True, null=True)
	report_description = models.TextField(blank=True, null=True)
	script_name = models.CharField(max_length=200, blank=True, null=True)
	filepath = models.CharField(max_length=250, blank=True, null=True)
	que_type = models.CharField(max_length=20, choices=QUE_TYPE, null=True, blank=True)
	email = models.CharField(max_length=500, blank=True, null=True)
	printer = models.ForeignKey(Printer, blank=True, null=True)
	fax = models.CharField(max_length=20, blank=True, null=True)
	current_job_status = models.CharField(max_length=50, choices=JOB_STATUS, null=True, blank=True)
	date_submitted = models.DateField(blank=True, null=True)
	time_submitted = models.TimeField(blank=True, null=True)
	date_finished = models.DateField(blank=True, null=True)
	time_finished = models.TimeField(blank=True, null=True)
	search_start_date = models.DateField(blank=True, null=True)
	search_end_date = models.DateField(blank=True, null=True)
	search_string = models.CharField(max_length=250, blank=True, null=True)
	search_status_type = models.CharField(max_length=50, null=True, blank=True)

	def __unicode__(self):
		return "%s - %s" % (self.report.report_type, self.que_type)

	class Meta:
		verbose_name = "single report"
		verbose_name_plural = "single reports"

		permissions = (
    		('view_singlereport', 'Can View single report'),
    	)

templates/report/report-type/add-list-report-tyep.html
{% extends "base.html" %}

{% block content %}

<div class="container shadow4 main-body">

<section class="row"  id="report-type">
	

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
		    	<h4>Report Type List</h4>
		  	</div>
		  	<div class="panel-body">
		  	<form name="report-type-form">
		  		<div class="input-group">
				  	{% for field in report_type_form %}
				  		{{ field }}
				  	{% endfor %}
				  	<div class="input-group-btn">
						<button class="btn btn-primary" type="submit">Add Report Type</button>
					</div>
				</div>
		  	</form>
			</div>
		</div>
	</div>

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-body">
				<div id="report-type-list">
				{% for report_type in report_types %}
					{% include "report/report-type/add-report-type-partial.html" %}
				{% endfor %}
				</div>
			</div>
		</div>

	</div>

{% include "modals/edit-modal.html" %}


<script type="text/javascript">
	(function(){

		$("a.report-type-edit").on("click", function(e){
			e.preventDefault();
			// com_id = $(this).data("id");
		    url = $(this).attr("href");
			mdal = $('#editModal');
			mdal.on("shown.bs.modal", function(){
				$("#editModal .modal-content").load(url);
				console.log(url);
			}).modal();

			return false;
		});

		$("form[name='report-type-form']").on("submit", function(e){
			e.preventDefault();
			form_data = $(this).serialize();

			$.ajax({
				type: "POST",
				url: "/report/report-type/add/",
				data: form_data,
				success: function(rdata) {
					$("#report-type-list").append(rdata);
					console.log(rdata);
				},
				errors: function() {

				}
			})

		})

	})(jQuery)


</script>



</section>
</div>


{% endblock content %}
	

templates/report/report-type/add-report-type-partial.html
<span class="label label-danger {{ report_type.id }}">
	{{ report_type.report_type }}
	{% if perms.report.change_reporttype %}
		<a class="report-type-edit" href="/report/report-type/edit/{{ report_type.id }}/" 
			data-toggle="modal" data-target="#editModal"
			data-unit-mes-id="{{ report_type.id }}"><i class="glyphicon glyphicon-edit"></i></a>
	{% endif %}
</span>

templates/report/report-type/edit-report-type-tmpl.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Edit Report Type</h4>
</div>
<form name="report-type" action="/report/report-type/edit/{{ report_type_id }}/" method="post">{% csrf_token %}
<div class="modal-body" style="text-align: center;">
    
    <input type="hidden" name="report_type_id" value="{{ report_type_id }}">
    <table>
        <tr>
        {% for field in reprot_type_form %}
            <td>
                {{ field }}
            </td>
        {% endfor %}
        
        </tr>
    </table>
    
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default close-modal" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save changes</button>
</div>
</form>
<script type="text/javascript">
(function(){
    $("form[name='report-type']").on("submit", function(e){
        e.preventDefault();
        id = $("input[name='report_type_id']").val();
        $("#report-type-list span."+id).remove();
        console.log(id);
        
        form_data = $(this).serialize();
        $.ajax({
            type: "POST",
            url: $(this).attr("action"),
            data: form_data,
            success: function(rdata) {
                $( "button.close-modal" ).trigger( "click" );

                $("#report-type-list").prepend(rdata);

            }
        })

    })

})(jQuery)
    
</script>

templates/report/report-type/list-report-type.html
{% extends "base.html" %}

{% block content %}

<div class="container shadow4 main-body">

<section class="row"  id="report-type-list">
	

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
		    	<h4> Report Type List</h4>
		  	</div>
		  	<div class="panel-body">
		  		<table class="table">
			  		<tr>
			  			<td> ID </td>
			  			<td>Report Type </td>
			  			<td>Total Use</td>
			  			<td>Action</td>
			  			
			  		</tr>
			  		{% for report_type in report_types %}
			  			<tr>
				  			<td> {{ report_type.id }} </td>
				  			<td> {{ report_type.report_type }} </td>
				  			<td> {{ report_type.report_set.all.count }} </td>
				  			<td>
				  				<a class="report-type-delete" href="#" data-id="{{ report_type.id }}">delete</a>
				  			</td>
				  			
				  		</tr>
				  	{% empty %}
				  	<tr>
			  			<td colspan='4'> No Report Type found. </td>
			  		</tr>
				  	{% endfor %}
			  	</table>
		  	
			</div>
		</div>
	</div>


</section>

<script type="text/javascript">
(function(){
	$("#report-type-list a.report-type-delete").on("click", function(e){
		e.preventDefault();
		id = $(this).data("id");
		console.log(id);

		$.ajax({
			type: "POST",
			url: "/report/report-type/delete/",
			data: {
				'report_type_id': id,
			},
			success: function(rdata) {
				console.log(rdata);
				$("a[data-id='"+rdata+"']").closest("tr").remove();
			}
		})
	});

})(jQuery)

</script>
</div>


{% endblock content %}
	