events/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'events.views.list_event', name='event-list'),
    url(r'^search/$', 'events.views.search_events', name='events-list'),
    url(r'^list/$', 'events.views.list_event_api', name='event-list-api'),
    url(r'^add/$', 'events.views.add_event', name='add-event'),
    url(r'^edit/(?P<id>\w+)/$', 'events.views.edit_event', name='edit-events'),
    url(r'^delete/$', 'events.views.delete_event', name='delete-events'),
    url(r'^view/(?P<id>\w+)/$', 'events.views.events_details', name='events-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),
   
    url(r'^controllers/$', 'events.views.list_controller', name='controller-list'),
    url(r'^controller-list/$', 'events.views.controller_list', name='list-controller'),
    url(r'^controllers/add/$', 'events.views.add_controller', name='add-controller'),
    url(r'^controllers/edit/(?P<controller_name>[\w ,\']+)/$', 'events.views.edit_controller', name='edit-controller'),
    url(r'^controllers/delete/$', 'events.views.delete_controller', name='delete-controller'),
    url(r'^controllers/view/(?P<controller_name>[\w ,\']+)/$', 'events.views.controller_details', name='controller-details'),
    # url(r'event/filter/$', 'events.views.item_details_filtered', name='events-details-filtered'),


    url(r'^evententry/add/$', 'events.views.add_evententry', name='add-event-entry'),
    url(r'^evententry/delete/$', 'events.views.delete_evententry', name='delete-event-entry'),
    url(r'^evententry/edit/(?P<entryid>[\w ,\']+)/$', 'events.views.edit_evententry', name='edit-event-entry'),
    url(r'^evententry/view/(?P<entryid>[\w ,\']+)/$', 'events.views.view_evententry', name='view-event-entry'),
    url(r'^entry/list/$', 'events.views.list_evententry', name='list-event-entry'),
    
    url(r'^event-entry-list/$', 'events.views.list_evententry_api', name='list-event-entry-api'),


    url(r'^eventpayroll/add/$', 'events.views.add_eventpayroll', name='add-event-payroll'),
    url(r'^payroll/delete/$', 'events.views.delete_eventpayroll', name='delete-event-payroll'),
    url(r'^payroll/edit/(?P<serial_id>[\w ,\']+)/$', 'events.views.edit_eventpayroll', name='edit-event-payroll'),
    url(r'^payroll/view/(?P<serial_id>[\w ,\']+)/$', 'events.views.view_eventpayroll', name='view-event-payroll'),
    url(r'^payroll/list/$', 'events.views.list_eventpayroll', name='list-event-payroll'),
   
)

imeter24/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'imeter24.views.home', name='home'),

    url(r'^generate-pdf/$', 'imeter24.views.generate_pdf', name='generate-pdf'),

    url(r'^system-variable/$', 'imeter24.views.sys_variable', name='sys-variable'),
    
    url(r'^dashboard/$', 'imeter24.views.dashboard', name='user-dashboard'),

    url(r'^send-mass-mail/$', 'imeter24.views.send_mass_mail', name='send-mass-mail'),
    url(r'^mass-mail-status/$', 'imeter24.views.mass_mail_status', name='mass-mail-status'),
    url(r'^get-mass-mails/$', 'imeter24.views.get_mass_mails', name='get-mass-mail'),
    
    url(r'^group/add/$', 'imeter24.views.add_group', name='add-group'),
    url(r'^group/list/$', 'imeter24.views.list_group', name='list-group'),
    url(r'^group/delete/$', 'imeter24.views.delete_group', name='delete-group'),

    #======= Angular route ===========
    url(r'^userlist/$', 'scomuser.views.UserListApi', name='userlistapi'),

    url(r'^group/edit/(?P<group_id>\d+)/$', 'imeter24.views.edit_group', name='edit-group'),
    url(r'^group/view/(?P<group_id>\d+)/$', 'imeter24.views.group_details', name='view-group'),

    url(r'^group/update/$', 'imeter24.views.update_group', name='update-group'),
    url(r'^scomuser/', include('scomuser.urls')),
    url(r'^contacts/', include('contacts.urls')),
    # url(r'^inventory/', include('inventory.urls')),
    # url(r'^report/', include('report.urls')),
    # url(r'^events/', include('events.urls')),
    # url(r'^purchase/', include('purchase.urls')),

    url(r'^controllers/', include('controllers.urls')),


    # url(r'^schedule/', include('schedule.urls')),

    url(r'^statics/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.STATIC_ROOT}),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    )

report/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^list/$', 'report.views.list_report', name='report-list'),
    url(r'^list/api/$', 'report.views.list_report_api', name='report-list-api'),
    
    url(r'^add/$', 'report.views.add_report', name='add-report'),
    url(r'^delete/$', 'report.views.delete_report', name='delete-report'),
    url(r'^edit/(?P<id>[\w -]+)/$', 'report.views.edit_report', name='edit-report'),
    url(r'^view/(?P<id>[\w -]+)/$', 'report.views.report_details', name='report-details'),
    url(r'^view/api/(?P<id>[\w -]+)/$', 'report.views.report_details_api', name='report-details'),
    url(r'^view/$', 'report.views.report_view', name='report-view'),

    url(r'^recuring/add/$', 'report.views.add_recuring_report', name='add-recuring-report'),
    url(r'^recuring/delete/$', 'report.views.delete_recuring_report', name='delete-recuring-report'),
    url(r'^recuring/view/(?P<id>[\w -]+)/$', 'report.views.view_recuring_report', name='view-recuring-report'),
    url(r'^recuring/edit/(?P<id>[\w -]+)/$', 'report.views.edit_recuring_report', name='edit-recuring-report'),

    url(r'^singlejob/add/$', 'report.views.add_single_report', name='add-single-report'),
    url(r'^singlejob/view/(?P<id>[\w -]+)/$', 'report.views.view_single_report', name='view-single-report'),
    url(r'^singlejob/api/(?P<jobid>[\w -]+)/$', 'report.views.single_report_api', name='api-single-report'),
    url(r'^singlejob/edit/(?P<id>[\w -]+)/$', 'report.views.edit_single_report', name='edit-single-report'),
    url(r'^singlejob/delete/$', 'report.views.delete_single_report', name='delete-single-report'),

    url(r'^recuring/job/api/(?P<id>[\w -]+)/$', 'report.views.recuring_job_json', name='recuring-job-api'),

    url(r'^lists/$', 'report.views.recuring_report_list', name='list-recuring-report'),
    url(r'^recuring-job-list/$', 'report.views.list_recuring_job', name='report-recuring-list'),
    url(r'^single-job-list/$', 'report.views.list_single_job', name='report-single-list'),

    url(r'^printer/list/$', 'report.views.list_printer', name='list-printer'),
    url(r'^printer/list/api/$', 'report.views.list_printer_api', name='list-printer-api'),
    url(r'^printer/add/$', 'report.views.add_printer', name='add-printer'),
    url(r'^printer/view/(?P<printer_id>[\w -]+)/$', 'report.views.view_printer', name='view-printer'),
    url(r'^printer/edit/(?P<printer_id>[\w -]+)/$', 'report.views.edit_printer', name='edit-printer'),
    url(r'^printer/delete/$', 'report.views.delete_printer', name='delete-printer'),


)

report/models.py
from django.db import models
from report.choices import *

# Create your models here.


# class ReportType(models.Model):
# 	report_type = models.CharField(max_length=20, null=True, blank=True)
# 	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

# 	def __unicode__(self):
# 		return self.report_type

# 	# def natural_key(self):
# 	# 	return self.report_type

# 	class Meta:
# 		verbose_name = "Report Type"
# 		verbose_name_plural = "Report Types"

# 		permissions = (
#     		('view_reporttype', 'Can View Report Type'),
#     	)


# class Printer(models.Model):
# 	printer_name = models.CharField(max_length=20, null=True, blank=True)
# 	is_active = models.BooleanField(verbose_name="Is Active", blank=False, default=True)

# 	def __unicode__(self):
# 		return self.printer_name

# 	# def natural_key(self):
# 	# 	return self.printer_name

# 	class Meta:
# 		verbose_name = "Printer Name"
# 		verbose_name_plural = "Printer Names"

# 		permissions = (
#     		('view_printer', 'Can View Printer'),
#     	)

class Printer(models.Model):
	printer_id = models.CharField(max_length=50, primary_key=True)
	# printer_name = models.CharField(max_length=20, null=True, blank=True)
	network_que_location = models.CharField(max_length=200, null=True, blank=True)
	printer_type = models.CharField(max_length=25, choices=PRINTER_TYPE, null=True, blank=True)
	printer_status = models.CharField(max_length=20, choices=PRINTER_STATUS, null=True, blank=True)
	

	def __unicode__(self):
		return self.printer_id

	# def natural_key(self):
	# 	nk = { 'printer_name': self.printer_id}
	# 	return (nk)

	class Meta:
		verbose_name = "Printer"
		verbose_name_plural = "Printers"

		permissions = (
    		('view_printer', 'Can View Printer'),
    	)


class Report(models.Model):
	report_type = models.CharField(max_length=50, blank=True, null=True)
	# printer = models.ForeignKey(Printer, blank=True, null=True)
	destination_type = models.CharField(max_length=20, choices=QUE_TYPE, null=True, blank=True)
	# status = models.CharField(max_length=20, choices=STATUS, null=True, blank=True)
	comments = models.TextField(blank=True, null=True)
	# start_date = models.DateField(blank=True, null=True)
	# end_date = models.DateField(blank=True, null=True)
	# rang = models.CharField(max_length=50, blank=True, null=True)
	python_script = models.CharField(max_length=200, blank=True, null=True)
	search_string = models.CharField(max_length=250, blank=True, null=True)

	def __unicode__(self):
		return self.report_type

	class Meta:
		verbose_name = "report"
		verbose_name_plural = "reports"

		permissions = (
    		('view_report', 'Can View report'),
    	)

class RecuringReport(models.Model):
	report = models.ForeignKey(Report, blank=True, null=True)
	report_description = models.TextField(blank=True, null=True)
	script_name = models.CharField(max_length=200, blank=True, null=True)

	que_type = models.CharField(max_length=20, choices=QUE_TYPE, null=True, blank=True)
	email = models.CharField(max_length=500, blank=True, null=True)
	printer = models.ForeignKey(Printer, blank=True, null=True, default=None)
	fax = models.CharField(max_length=20, blank=True, null=True)
	current_job_status = models.CharField(max_length=50, choices=JOB_STATUS, null=True, blank=True)
	date_submitted = models.DateField(blank=True, null=True)
	time_submitted = models.TimeField(blank=True, null=True)
	date_finished = models.DateField(blank=True, null=True)
	time_finished = models.TimeField(blank=True, null=True)
	# script_name = models.CharField(max_length=50, blank=True, null=True)
	unix_que = models.CharField(max_length=100, blank=True, null=True)
	comment = models.TextField(blank=True, null=True)

	schedule_type = models.CharField(max_length=15, choices=(('weekly', 'Weekly'), ('daily', 'Daily'), ('randomdays', 'Random week days')))
	week_day = models.CharField(max_length=200, blank=True, null=True)
	randomdays = models.CharField(max_length=200, blank=True, null=True)
	daytime = models.CharField(max_length=15, blank=True, null=True)
	search_string = models.CharField(max_length=250, blank=True, null=True)

	def __unicode__(self):
		return "%s - %s" % (self.report.report_type, self.que_type)

	class Meta:
		verbose_name = "recuring report"
		verbose_name_plural = "recuring reports"

		permissions = (
    		('view_recuringreport', 'Can View recuring report'),
    	)


class SingleReport(models.Model):
	report = models.ForeignKey(Report, blank=True, null=True)
	report_description = models.TextField(blank=True, null=True)
	script_name = models.CharField(max_length=200, blank=True, null=True)
	filepath = models.CharField(max_length=250, blank=True, null=True)
	que_type = models.CharField(max_length=20, choices=QUE_TYPE, null=True, blank=True)
	email = models.CharField(max_length=500, blank=True, null=True)
	printer = models.ForeignKey(Printer, blank=True, null=True)
	fax = models.CharField(max_length=20, blank=True, null=True)
	current_job_status = models.CharField(max_length=50, choices=JOB_STATUS, null=True, blank=True)
	date_submitted = models.DateField(blank=True, null=True)
	time_submitted = models.TimeField(blank=True, null=True)
	date_finished = models.DateField(blank=True, null=True)
	time_finished = models.TimeField(blank=True, null=True)
	search_start_date = models.DateField(blank=True, null=True)
	search_end_date = models.DateField(blank=True, null=True)
	search_string = models.CharField(max_length=250, blank=True, null=True)
	search_status_type = models.CharField(max_length=50, null=True, blank=True)

	def __unicode__(self):
		return "%s - %s" % (self.report.report_type, self.que_type)

	class Meta:
		verbose_name = "single report"
		verbose_name_plural = "single reports"

		permissions = (
    		('view_singlereport', 'Can View single report'),
    	)

templates/report/add-report.html
{% extends "base.html" %}

{% block content %}

<div class="container shadow4 main-body" ng-app="demoApp">

<section class="row"  id="report" ng-controller="AddReportController">
	

	<div class="col-md-6 col-md-offset-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
		    	<h4>Add Report Type</h4>
		  	</div>
		  	<div class="panel-body">
			  	<form name="report-form" action="/report/add/" method="POST">{% csrf_token %}
			  		<table class="add-user-table">
				  		<tbody><tr>
				  				<td><label for="id_report_type">Report type:</label></td>
				  				<td><input class="form-control" id="id_report_type" maxlength="100" name="report_type" placeholder="Report Type" type="text"></td>
				  			</tr>
				  		
				  		
				  			<tr>
				  				<td><label for="id_comments">Comments:</label></td>
				  				<td><textarea class="form-control" cols="40" id="id_comments" name="comments" placeholder="Comments" rows="2"></textarea></td>
				  			</tr>
				  		
				  			<tr>
				  				<td><label for="id_python_script">Python script:</label></td>
				  				<td><input class="form-control" id="id_python_script" maxlength="200" name="python_script" placeholder="Python script" type="text"></td>
				  			</tr>
				  		
				  		
					<tr>
						<td colspan="2">
							<button type="submit" class="btn btn-primary btn-lg form-control login-btn">Add Report Type</button>
						</td>
					</tr>
					</tbody>
				  	
					</table>
			  	</form>
			</div>
		</div>
	</div>

</section>
</div>
<script type="text/javascript">

var demoApp = angular.module("demoApp", [], function ($interpolateProvider) {
        $interpolateProvider.startSymbol("{[{");
        $interpolateProvider.endSymbol("}]}");
});
demoApp.controller("AddReportController", ['$scope', '$http', function ($scope, $http){

}]);


(function(){
	$(".datetimepicker").datepicker();
})(jQuery)

</script>

{% endblock content %}
	

templates/report/recuring-job-edit2.html
{% extends "base.html" %}

{% block content %}

<div class="container shadow4 main-body" ng-app="demoApp">

<section class="row"  id="report" ng-controller="EditRecuringJobController">
	

	<div class="col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
		    	<h4>Edit Recuring Job</h4>
		  	</div>
		  	<div class="panel-body" >
			  	<form name="report-form" action="{[{action}]}" method="POST">{% csrf_token %}
			  		<table class="add-user-table">
				  		<tr>
			  				<td><label for="id_report">Report:</label></td>
			  				<td>
			  					<select class="form-control" ng-model="report_type" id="id_report" name="report" ng-selected="{[{report_type}]}" ng-change="getReport(report_type)">
									<option value="0">---------</option>
									<option ng-repeat="report in reports"  value="{[{report.id}]}" data-id="{[{job.report.id}]}"
									>{[{report.report_type}]}</option>
									
								</select>
							</td>
				  		</tr>
				  		<tr>
			  				<td><label for="id_report_description">Report description:</label></td>
			  				<td><textarea class="form-control" cols="40" id="id_report_description" name="report_description" placeholder="Report Description" required="False" rows="2" readonly>{[{ comments }]}</textarea></td>
			  			</tr>
			  			<tr>
			  				<td><label for="id_script_name">Script name:</label></td>
			  				<td><input class="form-control" id="id_script_name" maxlength="200" name="script_name" placeholder="Report Description" type="text" value="{[{ python_script }]}" readonly></td>
			  			</tr>

			  			<tr>
			  				<td><label for="id_que_type">Que Type:</label></td>
		  					<td>
		  						<select class="form-control" id="id_que_type" name="que_type" ng-model="que_type" ng-selected="{[{que_type}]}">
									<option value="email">Email</option>
									<option value="printer">Printer</option>
									<option value="fax">Fax</option>
									
								</select>
							</td>
			  			</tr>

			  			<tr ng-show="que_type=='email'">
			  				<td><label for="id_email">Email:</label></td>
			  				<td>
			  					<input class="form-control" id="id_email" value="{[{que_type_email}]}" maxlength="500" name="email" placeholder="Email" type="text">
			  				</td>
			  			</tr>

			  			<tr ng-show="que_type=='printer'">
			  				<td><label for="id_printer">Printer:</label></td>
			  					<td>
			  						<select class="form-control" id="id_printer" name="printer" ng-model="que_type_printer" >
										
										<option ng-repeat="report in printers" value="{[{report.printer_id}]}" ng-selected="{[{que_type_printer}]}">{[{report.printer_id}]}</option>
										
									</select>
								</td>
			  			</tr>

			  			<tr ng-show="que_type=='fax'">
			  				<td><label for="id_fax">Fax:</label></td>
			  				<td><input class="form-control" id="id_fax" maxlength="500" value="{[{que_type_fax}]}" name="fax" placeholder="Fax number" type="text"></td>
			  			</tr>

			  			<tr>
			  				<td><label for="id_current_job_status">Current job status:</label></td>
			  					<td>
			  						<select class="form-control" id="id_current_job_status" name="current_job_status" ng-model="current_job_status" ng-selected="{[{current_job_status}]}">
				  						<option value="new">New</option>
				  						<option value="inprogress">In Progress</option>
				  						<option value="error">Error</option>
				  						<option value="completed">Completed</option>
				  					</select>
			  					</td>
			  			</tr>

			  			<tr>
			  				<td><label for="id_date_submitted">Date Submitted:</label></td>
			  				<td>
			  					<input class="form-control" id="id_date_submitted" value="{[{date_submitted}]}" name="date_submitted" placeholder="Date submitted" type="text" ng-model="date_submitted" jqdatepicker></td>
		  				</tr>
		  			
		  				<tr>
		  					<td><label for="id_time_submitted">Time Submitted:</label></td>
		  					<td><input class="form-control timepicker ui-timepicker-input" id="id_time_submitted" name="time_submitted" placeholder="time submitted" type="text" value="{[{time_submitted}]}" autocomplete="off"></td>
		  				</tr>
		  			
		  				<tr>
		  					<td><label for="id_date_finished">Date finished:</label></td>
		  					<td><input class="form-control" id="id_date_finished" value="{[{date_finished}]}" name="date_finished" placeholder="Date Finished" type="text" ng-model="date_finished" jqdatepicker></td>
		  				</tr>
		  			
		  				<tr>
		  					<td><label for="id_time_finished">Time finished:</label></td>
		  					<td><input class="form-control timepicker ui-timepicker-input" id="id_time_finished" name="time_finished" placeholder="time finished" type="text" value="{[{time_finished}]}" autocomplete="off"></td>
		  				</tr>


			  			<tr>
			  				<td><label for="id_unix_que">Unix Que:</label></td>
			  				<td><input class="form-control" value="{[{job.unix_que}]}" id="id_unix_que" maxlength="50" name="unix_que" placeholder="Unix Que" type="text"></td>
			  			</tr>
			  			<tr>
			  				<td><label for="id_schedule_type">Schedule type:</label></td>
			  				<td>
			  					<select class="form-control" id="id_report_type" name="schedule_type" ng-model="schedule_type" ng-selected="{[{ schedule_type }]}">
			  						<option value="">---------</option>
			  						<option value="weekly">Weekly</option>
			  						<option value="daily">Every Day</option>
			  						<option value="randomdays">Random week days</option>
			  					</select>
			  				</td>
			  			</tr>

			  			<tr ng-show="schedule_type=='weekly'">
			  				<td><label for="id_week_day">Choose Week day</label></td>
			  				<td>
			  					<select class="form-control" id="id_week_day" ng-model="week_day" name="week_day">
			  						<option ng-repeat="day in week_days" value="{[{ day }]}">{[{ day }]}</option>
			  					</select>
			  				</td>
			  			</tr>

			  			<tr ng-show="schedule_type=='randomdays'">
			  				<td><label for="id_randomdays">Choose days</label></td>
			  				<td width="75%">
			  					
			  					<span ng-repeat="day in week_days" style="display:inline-block;" ng-model="test">
			  						<input type="checkbox" value="{[{day}]}" ng-checked="choosendays.indexOf(day) > -1" class="week_days"> {[{ day }]} 
			  					</span>
			  					
			  					<input type="text" name="randomdays" class="form-control" ng-model="selected_days" readonly>
			  				</td>
			  			</tr>

			  			<tr ng-show="schedule_type=='randomdays' || week_day || daily ">
			  				<td><label for="id_daytime">Choose your time</label></td>
			  				<td width="75%">
			  					<input class="form-control timepicker ui-timepicker-input" value="{[{daytime}]}" id="id_daytime" name="daytime"  type="text">
			  				</td>
			  			</tr>
				  		
						<tr>
							<td colspan="2">
								<button type="submit" class="btn btn-primary btn-lg form-control login-btn">Update Recuring Job</button>
							</td>
						</tr>
					</table>
			  	</form>
			</div>
		</div>
	</div>

	<div class="col-md-6" >
		<div class="panel panel-primary" ng-show="show_report">
			<div class="panel-heading">
		    	<h4>Report Details</h4>
		  	</div>
		  	<div class="panel-body" >
		  		<table class="table">
		  			<tr>
		  				<td>Report ID</td>
		  				<td>{[{ report_type_id }]}</td>
		  			</tr>
		  			
		  			<tr>
		  				<td>Comments</td>
		  				<td>{[{ comments }]}</td>
		  			</tr>
		  			<tr>
		  				<td>Python script</td>
		  				<td>{[{ python_script }]}</td>
		  			</tr>
		  			

		  		</table>
		  	</div>
		 </div>

	</div>

</section>
</div>
<script type="text/javascript">
var demoApp = angular.module("demoApp", [], function ($interpolateProvider) {
        $interpolateProvider.startSymbol("{[{");
        $interpolateProvider.endSymbol("}]}");
});

demoApp.directive('jqdatepicker', function() {
    return {
        restrict: 'A',
        require: 'ngModel',
        link: function(scope, element, attrs, ngModelCtrl) {
            $(element).datepicker({
                dateFormat: 'yy-mm-dd',

                onSelect: function(date) {
                    var ngModelName = this.attributes['ng-model'].value;
                    scope[ngModelName] = date;
                    scope.$apply();
                }

            });
        }
    };
});
demoApp.controller("EditRecuringJobController", ['$scope', '$http', function ($scope, $http){

	$scope.init = function(){
		$http.get("/report/list/api/").success(function(data){
          	$scope.reports = data;
        });

        $http.get("/report/printer/list/api/").success(function(data){
        	$scope.printers = data;
        });

		var path = window.location.pathname;
		var segments = path.split("/");
		var jobid = segments[(segments.length-2)];
		
		var url = "/report/recuring/job/api/"+jobid+"/";
		$scope.action = "/report/recuring/edit/"+jobid+"/";
		
        $http.get(url).success(function(data){
   			
          	$scope.job = data;
          	$scope.report_type = data.report.id;
          	$scope.destination_type = data.report.destination_type;
          	$scope.comments = data.report.comments;
          	$scope.python_script = data.report.python_script;
          	
          	
          	$scope.report_description = data.report_description;
          	$scope.script_name = data.script_name;
          	$scope.que_type = data.que_type;

          	if(data.que_type == 'email') {
          		$scope.que_type_email = data.email;
	          	$scope.que_type_printer = "";
	          	$scope.que_type_fax = "" ;	
          	} else if (data.que_type == 'printer') {
          		$scope.que_type_email = "";
	          	$scope.que_type_printer = data.printer;
	          	$scope.que_type_fax = "";
	          } else if (data.que_type == 'fax') {
	          	$scope.que_type_email = "";
	          	$scope.que_type_printer = "";
	          	$scope.que_type_fax = data.fax;
	          }
          	
          	$scope.current_job_status = data.current_job_status;
          	$scope.date_submitted = data.date_submitted;
          	$scope.time_submitted = data.time_submitted;
          	$scope.date_finished = data.date_finished;
          	$scope.time_finished = data.time_finished;

          	$scope.unix_que = data.unix_que;

          	$scope.schedule_type = data.schedule_type;
          	$scope.week_day = data.week_day;
          	$scope.selected_days = data.randomdays;
          	var randomdays = data.randomdays.split(",");
          	$scope.choosendays = randomdays;
          	$scope.daytime = data.daytime;
          	


        });
        $scope.keyExist = function(key,arr) {
        	console.log(key);
        	var a = arr.indexOf(key,0);
        	if (a != -1) {
        		return true;
        	} else {
        		return false;
        	}
        };

        $scope.getReport = function (report_id) {
	    	if (report_id != -1) {
	    		var url = "/report/view/api/"+report_id+"/";

		    	$http.get(url).success(function(data){
		   			 console.log(data);
		   			$scope.report_type_id = data.id;
		          	$scope.comments = data.comments;
		          	$scope.python_script = data.python_script;
		          	$scope.show_report = true;
		          	
		        });
	    	} else {
	    		$scope.show_report = false;

	    	}
	    	
	    	
	    }
        

        $scope.week_days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    }

    $scope.init();
    


}]);

</script>


<script type="text/javascript">
(function(){
	$(".datetimepicker").datepicker();
	$(".timepicker").timepicker();

	$(document).on("click", ".week_days", function(e){
		var day = $(this).val();
		var check = this.checked;
		var str = $("input[name='randomdays']").val();

		if (check) {
			if(str == ""){
				str = day	
			} else {
				str += "," + day
			}
			$("input[name='randomdays']").val(str);
		} else {
			var strarray = str.split(",");
			console.log(strarray);
			arr2 = strarray.splice( strarray.indexOf( day ), 1 );
			var newstr = strarray.join(",");
			$("input[name='randomdays']").val(newstr);
		}
		

	});

})(jQuery)
</script>
{% endblock content %}
	

templates/report/search-report.html
{{ lookup_form.media.css }}
{{ lookup_form.media.js }}

<section class="row" id="report-search">
	<div class="col-md-6">
		<form name="contact-filter" action="/report/view/" method="post">{% csrf_token %}
			<div class="input-group">
				{% for field in lookup_form %}
					{{ field }}
				{% endfor %}
				<span class="input-group-btn">
					<button class="btn btn-default" type="submit">Filter</button>
		      	</span>
	      	</div>
		</form>
	</div>
		
</section>